### ISSUE TITLE
Pan Niepolski - Protokół założycielski

### ISSUE THREAD

**Issue by bartkow** [projekt-zespolowy-pk/projekt#1]
Wraz z zastępcą Panem @damraj, zarządziliśmy, że Pan @Niepolski tworzy protokół założycielski.
Termin wykonania 01-03-2016 9:15

**Comment by damraj** [comment]
Robi Pan.

**Comment by niepolski** [comment]
Protokół założycielski

1. Grupa projektowa

W skład grupy wchodzą:

Bartosz Kowalik
Bartosz Niepolski
Damian Rajner
Michał Mazgazjski

Grupa ma za zadanie stworzenia projektu programistyczngo na podstawie tematu, który został wcześniej wybrany. W skład projektu wchodzi dokumentacja oaz gotowa aplikacja do działania.

Grupa nazywać się będzie: Syryjczycy

Liderem grupy będzie: Bartosz Kowalik 

2. Cel projektu
Celem projektu grupy jest stworzenie aplikacji, która pozwala na szybszy i bardziej dynamiczny sposób zarządzania sklepem komputerowym.

3. Obowiązki członków grupy
- Każdy z członków ma obowiązek wypełniać zadania.
- Każdy członek musi przestrzegać zasad które zosały wcześniej ustalone.
- Każdy ma prawo do zgłaszania własnych pomysłów odnośnie projektu.

4. Obowiązki lidera projektu
- Przy przekazywaniu projektu jest odpowiedzialny za całą grupę.
- Jako jedyny rozmawia z Odbiorcą.
- Nic nie może być wdrożne do projektu bez jego autoryzacji.

5. Kary
- W przypadku nie wykonywania zadań, członek grupy dostanie ostrzeżenie od Kierowniku grupy.
- Jeżeli osoba w dalszym ciągu nie podejmie się pracy, zostanie to zgłoszone prowadzącemu.
- Osoba która nie przestrzega zasad umiera(zostanie wydalona z grupy).
- Nie ma możliwości zmartwychwstania.

**Comment by bartkow** [comment]
Dziękuję.
Zamykam.

Pozdrawiam
D.G.

**Comment by damraj** [comment]
Zgodnie z zaleceniem Kierownika składam zażalenie.
Pan Niepolski zamiast pracować przegląda strone internetowe dotyczące nieprzyjemnych rzeczy.

**Comment by bartkow** [comment]
@damraj, odnotuje to w protokole.
